Fix NPE:
java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because "input" is null
        at com.dsh105.echopet.compat.api.entity.data.PetDataParser$BooleanParser.parse(PetDataParser.java:51) ~[EchoPet.jar:?]
        at com.dsh105.echopet.compat.api.entity.data.PetDataParser$BooleanParser.parse(PetDataParser.java:43) ~[EchoPet.jar:?]
        at com.dsh105.echopet.api.FileStorageManager.createRider(FileStorageManager.java:219) ~[EchoPet.jar:?]
        at com.dsh105.echopet.api.FileStorageManager.create(FileStorageManager.java:189) ~[EchoPet.jar:?]
        at com.dsh105.echopet.api.FileStorageManager.lambda$load$4(FileStorageManager.java:149) ~[EchoPet.jar:?]
        at com.dsh105.echopet.compat.api.plugin.action.SyncBukkitAction.lambda$execute$0(SyncBukkitAction.java:59) ~[EchoPet.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.2.jar:git-Paper-309]
        at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.2.jar:git-Paper-309]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1470) ~[paper-1.20.2.jar:git-Paper-309]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.2.jar:git-Paper-309]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1379) ~[paper-1.20.2.jar:git-Paper-309]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156) ~[paper-1.20.2.jar:git-Paper-309]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-309]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]