Fix NPE:
com.destroystokyo.paper.exception.ServerInternalException: Entity threw exception at world:34.13330363716044,112.40063227433109,176.01160793550775
	at net.minecraft.world.level.World.a(World.java:1316)
	at net.minecraft.server.level.WorldServer.lambda$tick$8(WorldServer.java:900)
	at net.minecraft.world.level.entity.EntityTickList.a(EntityTickList.java:42)
	at net.minecraft.server.level.WorldServer.a(WorldServer.java:880)
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1548)
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1379)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1156)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.craftbukkit.v1_20_R2.entity.CraftPlayer.getHandle()" because the return value of "com.dsh105.echopet.compat.api.entity.nms.IEntityPet.getPetOwner()" is null
	at EchoPet.jar//com.dsh105.echopet.compat.nms.v1_20_2.entity.ai.PetGoalFollowOwner.canContinueToUse(PetGoalFollowOwner.java:83)
	at EchoPet.jar//com.dsh105.echopet.compat.api.ai.PetGoalWrapper.canContinueToUse(PetGoalWrapper.java:51)
	at EchoPet.jar//com.dsh105.echopet.compat.api.ai.PetGoalSelector.tick(PetGoalSelector.java:100)
	at EchoPet.jar//com.dsh105.echopet.compat.nms.v1_20_2.entity.ai.GoalSelectorWrapper.a(GoalSelectorWrapper.java:53)
	at net.minecraft.world.entity.Mob.inactiveTick(Mob.java:228)
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1388)
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:1309)
	at net.minecraft.server.level.ServerLevel.lambda$tick$8(ServerLevel.java:900)
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42)
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:880)
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1548)
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446)
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1379)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1156)
	... 2 more